### ISSUE TITLE
"Application error null" into 'IntroActivity'

### ISSUE THREAD

**Issue by huanjulu** [KotlinID/Movin#1]
hi , try run this project ,
and its message me that "Application error null" into 'IntroActivity'
and i have no found where  this error came .
can i get some info about this issue ?
thank u

**Comment by putraxor** [comment]
Hi @isicout  can you provide more info about the error message
Don't forget to change the `API_KEY` inside `MovinConfig.kt`

**Comment by huanjulu** [comment]
okay  . sure that  the `API_KEY ` cause this issue .
and can you provide test key with me ? or you  can tell me where can i got  it ? 

just run this project .  and  thanks  for your code .

**Comment by putraxor** [comment]
Sure, this project for educational uses only, you can use this one `6705bca6d690af52e315ce05b3c774d2`, however you can get your own by registering to [www.themoviedb.org](https://www.themoviedb.org/) and find it over here [https://www.themoviedb.org/settings/api](https://www.themoviedb.org/settings/api)

**Comment by huanjulu** [comment]
Okay ,
thanks!!
